# Generated by Django 6.0.2 on 2026-02-09 12:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='О нас / О компании / Наша история', max_length=150, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(null=True, upload_to='staff/', verbose_name='Фото')),
                ('position', models.CharField(max_length=80, verbose_name='Должность')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience', models.IntegerField(verbose_name='Стаж работы (лет)')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Сотрудниках',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка на соцсеть')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
        migrations.CreateModel(
            name='ImagesStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='imagesStaff/', verbose_name='Фото')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'доп фото',
                'verbose_name_plural': 'Дополнительные фотографии',
            },
        ),
    ]
