# Generated by Django 4.2.27 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social_whatsapp',
            field=models.CharField(blank=True, help_text='https://wa.me/996703016683/', max_length=255, null=True, verbose_name='Ссылка на whatsapp'),
        ),
    ]
