# Generated by Django 4.2.27 on 2026-01-26 13:18

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='О нас / О компании / Наша история', max_length=150, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=80, verbose_name='Должность')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience', models.IntegerField(verbose_name='Стаж работы (лет)')),
            ],
            options={
                'verbose_name_plural': 'Сотрудниках',
            },
        ),
    ]
