# Generated by Django 4.2.27 on 2026-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='staff/', verbose_name='Фото'),
        ),
    ]
