# Generated by Django 4.2.27 on 2026-01-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка на соцсеть')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
