# Generated by Django 4.2.27 on 2026-01-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='about.staff', verbose_name='Сотрудник'),
        ),
    ]
