# Generated by Django 4.2.27 on 2026-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_sociallink_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
