# Generated by Django 4.2.27 on 2026-01-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_staff_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='imagesStaff/', verbose_name='Фото')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'доп фото',
                'verbose_name_plural': 'Дополнительные фотографии',
            },
        ),
    ]
